services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: go-backend
    ports:
      - "8080:8080"
    working_dir: /app

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "30000:8080"
    environment:
      SWAGGER_JSON: /swagger/openapi.yml
    volumes:
      - ./openapi.yml:/swagger/openapi.yml
