openapi: 3.0.3
info:
  title: Reorder API
  description: Reorder API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /reorder:
    post:
      summary: reorder texts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextsRequest'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextsResponse'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Missing 'texts' field in request body"

components:
  schemas:
    TextsRequest:
      type: object
      required:
        - texts
      properties:
        texts:
          type: array
          items:
            type: string
          example: ["olHel", "rowld!"]
    TextsResponse:
      type: object
      properties:
        texts:
          type: array
          items:
            type: string
          example: ["Hello", "world!"]
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Some error occurred"