openapi: 3.0.3
info:
  title: Reorder API
  description: Reorder API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /reorder:
    post:
      summary: reorder text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TextRequest'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextResponse'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Missing 'text' field in request body"

components:
  schemas:
    TextRequest:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          example: は、報デ情ーとタリデテパィークデるす散にしタ記分 式をィ各ス方で録すて。1もが障故し台て、りリれクのデデ残さパティス録たにィ記ー っデタてを使ーこ可旧るで能タ復とあを、デー数ク格てをけ納のるめた複ィす分タにデス、時がセアスでに上よクのす特るすみとこすとり徴性が能こ書き同向る読。
    TextResponse:
      type: object
      properties:
        text:
          type: string
          example: 各パーティションに分散してデータを記録します。各データは複数のストレージに複製されるため、1台が故障してもデータ復旧が可能です。旧データも残っているため、必要に応じて過去のデータを利用できます。\n\nこの方式の特徴は、複数のパーティションにデータを分散して格納することで、アクセス時の負荷を分散できる点です。読み書きの性能向上が期待できます。\n
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Some error occurred"

